app = 'dohac-apis'
primary_region = 'syd'

[build]

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = 'suspend'
auto_start_machines = true
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
